### ISSUE TITLE
Add the token key into url

### ISSUE THREAD

**Issue by ikhalilatteib** [plusclouds/leov4.common_domains.validator#9]
Add a **token** key to the url like the example below

http://example.com/api/domain?domain=http://niyel.com.tr&token=

if the token is null we check token from the file "/.well-known/validation.txt".

@emir-ekin-ors

**Comment by ibrahimozkn** [comment]
Doesn't this conflict with the primary purpose of this project? We aim to ensure that the domain belongs to the person who holds the token. By allowing the token to be provided inside the request without checking DNS records or HTTP files of the domain, anyone who has obtained the token through unauthorized means could validate the domain without actually owning it.

**Comment by yakari007** [comment]
@ibrahimozkn You are right. The intention of this issue was explained wrong. @ikhalilatteib will create a new issue for this.
